# This is a basic workflow to help you get started with Actions

name: Manual deploy test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch_to_deploy:
        description: "[REQUIRED] Branch to deploy"
        required: true
        default: master
      env_to_deploy:
        description: "[REQUIRED] ENV to deploy"
        required: true
        default: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: "Validate input"
        run: |
          ENV_TO_DEPLOY = ${{ github.event.inputs.env_to_deploy }}
          if [[ $ENV_TO_DEPLOY -ne "dev" || $ENV_TO_DEPLOY -ne "dev2" || $ENV_TO_DEPLOY -ne "dev3" ]]
          then echo "Env to deploy can be dev, dev2 or dev3!" && exit 1
          fi
      
      - name: Setup env for dev
        if: ${{ github.event.inputs.env_to_deploy == 'dev' }}
        run: |
          echo "target_dir=my-app-dev" >> $GITHUB_ENV
          echo "api_uri=app-dev" >> $GITHUB_ENV
          echo "db_host=DEV_DB_HOST" >> $GITHUB_ENV
      - name: Setup env for dev2
        if: ${{ github.event.inputs.env_to_deploy == 'dev2' }}
        run: |
          echo "target_dir=my-app-dev2" >> $GITHUB_ENV
          echo "api_uri=app-dev2" >> $GITHUB_ENV
          echo "db_host=DEV2_DB_HOST" >> $GITHUB_ENV
      - name: Setup env for dev3
        if: ${{ github.event.inputs.env_to_deploy == 'dev3' }}
        run: |
          echo "target_dir=my-app-dev3" >> $GITHUB_ENV
          echo "api_uri=app-dev3" >> $GITHUB_ENV
          echo "db_host=DEV3_DB_HOST" >> $GITHUB_ENV
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Branch ${{ github.event.inputs.branch_to_deploy }} and ENV ${{ github.event.inputs.env_to_deploy }}
          echo "dir=${{ env.target_dir }}; uri=${{ env.api_uri }}; host=${{ env.db_host }}"
