# This is a basic workflow to help you get started with Actions

name: Manual deploy test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch_to_deploy:
        description: "[REQUIRED] Branch to deploy"
        required: true
        default: master
      env_to_deploy:
        description: "[REQUIRED] ENV to deploy"
        required: true
        default: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  if: ${{ github.event.inputs.env_to_deploy == 'dev2' }}
    env:
      DIR: "my-app-dev2"
      API_URI: "app-dev2"
      DB_HOST: "DEV2_DB_HOST"
  if: ${{ github.event.inputs.env_to_deploy == 'dev3' }}
    env:
      DIR: "my-app-dev3"
      API_URI: "app-dev3"
      DB_HOST: "DEV3_DB_HOST"
  if: ${{ github.event.inputs.env_to_deploy == 'dev' }}
    env:
      DIR: "my-app-dev"
      API_URI: "app-dev"
      DB_HOST: "DEV_DB_HOST"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Branch ${{ github.event.inputs.branch_to_deploy }} and ENV ${{ github.event.inputs.env_to_deploy }}
          echo "dir=${DIR}; uri=${API_URI}; host=${DB_HOST}"
