name: "[DEV, MANUAL, OPT] Deploy branch to dev"

on:
  workflow_dispatch:
    inputs:
      branch_to_deploy:
        description: "[REQUIRED] Branch to deploy on dev"
        required: true
        default: develop
      env_to_deploy:
        description: "[REQUIRED] Dev server to deploy the branch"
        required: true
        default: dev
jobs:
  deploy_to_dev:
    name: "Deploy to ${{ github.event.inputs.env_to_deploy }}"
    runs-on: ubuntu-latest
    steps:
      - name: "Get environemt for deploy"
        id: setup_deploy_env
        run: |
          pwd && ls
          json="$(cat .github/workflows/test.json)"
          deployEnvJson=$(echo $json | jq --arg inputEnv "${{ github.event.inputs.env_to_deploy }}" 'map(. | select(.deployEnv==$inputEnv) ) | .[0]')

          if [ -z deployEnvJson ]
          then
            echo "Available deployment environments are ${ json.*.deployEnv }" && exit 1
          fi

          echo "::set-output name=deployEnvJson::deployEnvJson"

      - name: "Setup common env vars"
        run: |
          echo "TARGET_DIR=my-app-${{ github.event.inputs.env_to_deploy }}" >> $GITHUB_ENV
          echo "API_URI=app-${{ github.event.inputs.env_to_deploy }}" >> $GITHUB_ENV
          echo "DOCKER_SUFFIX=-${{ github.event.inputs.env_to_deploy }}" >> $GITHUB_ENV

      - name: "Setup env for deploy"
        run: |
          deployEnv=${{ fromJson(steps.get_env_data.outputs.deployEnvJson) }}
          echo "DOCKER_PORT=${deployEnv.port}" >> $GITHUB_ENV
          echo "DEV_DB_HOST=${deployEnv.db_host}" >> $GITHUB_ENV
